# Use postgres/example user/password credentials

services:

  db:
    image: postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./bank.sql:/docker-entrypoint-initdb.d/bank.sql
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    stdin_open: true
    tty: true

volumes:
  db_data:
  ollama: